name: Build
on:
  push:
    branches:
      - main
      - feature/*
      - release/*
      - bugfix/*
      - improvement/*
jobs:
  build-job:
    name: Build project
    runs-on: windows-2022
    steps:
      - name: Set up build environment (install conan)
        run: pip install conan==1.54.0
      - name: Checkout application source code
        uses: actions/checkout@v4
      - name: Build application
        run: cmake -P cmake/scripts/build.txt
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build
          if-no-files-found: error
