name: Test
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
jobs:
  on-success:
    name: Test application
    runs-on: windows-2022
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download solution artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          name: solution-artifacts
          run_id: ${{ github.event.workflow_run.id }}
          path: build
      - name: Run tests
        run: |
          cd build
          ctest -C Release -V
  on-failure:
    name: Skip test application
    runs-on: windows-2022
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Report skip reason
        run: echo 'The triggering workflow failed'
